# Generated by Django 5.2.7 on 2025-10-21 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomify_uap_app', '0004_bookingrequest'),
        ('roomify_uap_app', '0005_listing_occupied_listingview'),
    ]

    operations = [
    ]
